### ISSUE TITLE
hi the file ask me for last version which is 4.24 and i have 4.23 how i can fix this 

### ISSUE THREAD

**Issue by MSCreationAndMore** [sgeraldes/LightmassConfiguration#11]
hi the file ask me for last version which is 4.24 and i have 4.23 how i can fix this

**Comment by sgeraldes** [comment]
Change unreal version in the .bat file.

**Comment by cafeoh** [comment]
Hi Sebastian, don't want to reopen an issue for that, but I tried changing the version `set UnrealVersion=4.23`, but whenever I try to install it I get a bunch of missing .dlls and the engine refuses to start.

Any idea of what is happening?

Thanks! :smile:

**Comment by sgeraldes** [comment]
Sorry, I don't. I'm not longer using 4.23, but it was working fine. May want to roll back to a previous version.

**Comment by cafeoh** [comment]
Thank you, for posterity rolling back to [4eb9468 ](https://github.com/sgeraldes/LightmassConfiguration/commit/4eb94681d5c5b0f86bcfedcbf1f07720aa6dba17)fixed it
