### ISSUE TITLE
Please update it to 4.25

### ISSUE THREAD

**Issue by dkudrin** [sgeraldes/LightmassConfiguration#12]
Please update it to 4.25

**Comment by malochen** [comment]
plz 4.25

**Comment by Goury** [comment]
4.26

**Comment by saidmoya12** [comment]
UE 4.26 includes GPU Lightmap natively, but requires Ray RayTracing

**Comment by saidmoya12** [comment]
Alternatively, you can download manually or with HashCkeck.bat via the links below

UE4.25.4 
https://www.dropbox.com/sh/yymsusetmd3cx8m/AAB84i6yLLGwfPmWPL-9lB3ca?dl=1

UE4.26.1
https://www.dropbox.com/sh/967fls1i0g2frt9/AAAW6T7Bew7IRysQc0YXXpS-a?dl=1


Originally posted by **pax invictus** on [Luoshuang's GPULightmass forum](https://forums.unrealengine.com/development-discussion/rendering/1460002-luoshuang-s-gpulightmass/page126#post1826322)

My example code:
```sh
#HashCkeck.bat
...
set uGPULightmass4254u=https://www.dropbox.com/sh/yymsusetmd3cx8m/AAB84i6yLLGwfPmWPL-9lB3ca?dl=1
set uGPULightmass4261=https://www.dropbox.com/sh/967fls1i0g2frt9/AAAW6T7Bew7IRysQc0YXXpS-a?dl=1
```

**Comment by malochen** [comment]
> Alternatively, you can download manually or with HashCkeck.bat via the links below
> 
> UE4.25.4
> https://www.dropbox.com/sh/yymsusetmd3cx8m/AAB84i6yLLGwfPmWPL-9lB3ca?dl=1
> 
> UE4.26.1
> https://www.dropbox.com/sh/967fls1i0g2frt9/AAAW6T7Bew7IRysQc0YXXpS-a?dl=1
> 
> Originally posted by **pax invictus** on [Luoshuang's GPULightmass forum](https://forums.unrealengine.com/development-discussion/rendering/1460002-luoshuang-s-gpulightmass/page126#post1826322)
> 
> My example code:
> 
> ```shell
> #HashCkeck.bat
> ...
> set uGPULightmass4254u=https://www.dropbox.com/sh/yymsusetmd3cx8m/AAB84i6yLLGwfPmWPL-9lB3ca?dl=1
> set uGPULightmass4261=https://www.dropbox.com/sh/967fls1i0g2frt9/AAAW6T7Bew7IRysQc0YXXpS-a?dl=1
> ```

thanks so much .

**Comment by sgeraldes** [comment]
If you send me the hash for the files, I'll gladly do the updates. You need to run HashCheck and get the codes from the output. Post them here or just do a pull request and I'll merge it. 

Sorry but it's been a while since I last I used GPULightmass.

**Comment by sgeraldes** [comment]
Updated to 4.25.4
Marked as closed
