### ISSUE TITLE
Update to 4.26.1 Please

### ISSUE THREAD

**Issue by Arkitecton** [sgeraldes/LightmassConfiguration#14]
Can you please update it to 4.26.1?

ERRO: CPU Lightmass Kernel version is unknown.
INFO: EDITOR HASH: 7f1efbf7bf56b6682086bdace909b893

![image](https://user-images.githubusercontent.com/19477961/113136971-38488500-9239-11eb-9e0b-8bcf46881dac.png)

**Comment by sgeraldes** [comment]
Updated to 4.26.2
