### ISSUE TITLE
GPU Lightmass crashes editor on UE 4.26.2 Oculus branch

### ISSUE THREAD

**Issue by Jaydead** [sgeraldes/LightmassConfiguration#15]
Hi, not sure how major the changes are between the main and Oculus branches, but it used to work on earlier 4.25.4 version.

My issue is currently at this specific branch:
https://github.com/Oculus-VR/UnrealEngine/releases/tag/oculus-4.26.2-release-1.61.0-v29.0

Here's the the error prompt:
![Error1](https://user-images.githubusercontent.com/28712500/136761948-efe89766-6ff4-4021-9cfb-255453cecafb.jpg)

It doesn't load at all, just instantly gives this error when trying to start a project.

**Comment by sgeraldes** [comment]
I'm not sure how I can help. Looks like an issue with your specific build a GPU Lightmass. You may want to try the UE forums if you haven't done so.

**Comment by Jaydead** [comment]
Okay, thanks. 

This appeared after installing GPU lightmass, but perhaps it's something wrong with my current UE build.

**Comment by sgeraldes** [comment]
Although this script installs GPU lightmass, I have nothing to do with it. I just made the script to make things easier so people doesn't have to manually copy the files to the proper unreal folders. This script probably can't identify a custom build, neither I can't test it, so I wouldn't know which version matches your build.
There is people in the forum that can help you with GPU lightmass itself.
