### ISSUE TITLE
Support latest GPU lightmass version (UE4.21 + Turing GPUs support)

### ISSUE THREAD

**Issue by Rbn3D** [sgeraldes/LightmassConfiguration#2]
Hi!

It's the latest version of GPU lightmass going to be supported? It adds support for 4.21 and it now works for Turing cards. Would be nice to have a simple installer/unistaller.

Thanks for your work on this 👍

**Comment by sgeraldes** [comment]
Script updated to work with 4.21 Unified Settings. Removed all other options also since there is no other binary distribution now other than Unified.
Updated Min GPU Drivers version requirement also.
Please try and let me know if it works.
