### ISSUE TITLE
Problem in ue 4.23

### ISSUE THREAD

**Issue by raiden1983** [sgeraldes/LightmassConfiguration#5]
Hi. I have a problem. When i run file i have this issue. Can you help me?
![image](https://user-images.githubusercontent.com/9402994/66683570-14c20100-ec78-11e9-8156-8b7f1f0d1fe8.png)

**Comment by crazyramirez** [comment]
Open lightmass .bat with a text editor ando check line:
set UnrealVersion=4.23

**Comment by raiden1983** [comment]
I think it looks okay 
![image](https://user-images.githubusercontent.com/9402994/67164364-fcd63580-f379-11e9-88a2-2bb4a9ba5fc9.png)

**Comment by sgeraldes** [comment]
It is a known issue. Has been brought into the forums as well. 
There are 2 reasons that I know of:
- Manual installation (from github, or other means)
- Faulty installation (reinstalling the epic launcher and unreal may fix it)

There is really nothing I can do on my side. The script is very simple, it uses reg.exe and looks for a registry key value in HKLM\Software\EpicGames\Unreal Engine\4.23 to understand what's the installation path. If you don't have registry read rights on that key (maybe try running the script directly from admin console), or the registry path is different (sometimes translations can change  the registry path), try using regedit to see if the key is there. Look into HKLM\Software\EpicGames\Unreal Engine\4.23

Cheers

**Comment by raiden1983** [comment]
Hi. I reinstal UE and now i have this
![image](https://user-images.githubusercontent.com/9402994/67599316-17405280-f770-11e9-9166-b140b5b2b3c5.png)

**Comment by sgeraldes** [comment]
Download URL was temporarily non-available. Fixed script to point to the right locations.
