### ISSUE TITLE
Lightmass is BROKEN

### ISSUE THREAD

**Issue by olivatooo** [sgeraldes/LightmassConfiguration#8]
This GPU lightmass configs are a totally mess, every light in every possible enviroment are BROKEN, visual glitches everywhere. For anyone reading this.. Just keep with your CPU Lightmass if you don't wanna have headache

**Comment by sgeraldes** [comment]
1. This has nothing to do with the script. 
2. If you have issues, go post your problem in the forums, someone more experienced will probably help you there.
3. If you don't know how to do something, start reading, don't blame the technology. 
Closed as invalid.
